#!/usr/bin/env bash
set -euo pipefail

ROOT="$(CDPATH='' cd -- "$(dirname "$0")/.." && pwd)"
TEST_ROOT="$(mktemp -d)"
HOLDER_PID=""
cleanup() {
  if [ -n "$HOLDER_PID" ]; then kill "$HOLDER_PID" 2>/dev/null || true; fi
  rm -rf "$TEST_ROOT"
}
trap cleanup EXIT HUP INT TERM

INSTALL_ROOT="$TEST_ROOT/bin"
DATA_ROOT="$TEST_ROOT/data"
mkdir -p "$INSTALL_ROOT"
printf '%s\n' 'production client sentinel' > "$INSTALL_ROOT/bp"
printf '%s\n' 'production helper sentinel' > "$INSTALL_ROOT/bp-host"

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

run_setup() {
  DEV_INSTALL_DIR="$INSTALL_ROOT" \
    BLACKPEPPER_DEV_TARGET_DIR="$ROOT/target" \
    BLACKPEPPER_DEV_DATA_DIR="$DATA_ROOT" \
    bash "$ROOT/scripts/setup.sh" "$@"
}

# An existing launcher is user data unless its complete content matches a
# launcher generated by this installer (including the legacy launcher).
printf '%s\n' 'unrelated bp-dev sentinel' > "$INSTALL_ROOT/bp-dev"
if run_setup >"$TEST_ROOT/unrelated.log" 2>&1; then
  printf '%s\n' 'unrelated bp-dev was unexpectedly overwritten' >&2
  exit 1
fi
grep -F 'refusing unrelated existing bp-dev' "$TEST_ROOT/unrelated.log" >/dev/null
test "$(cat "$INSTALL_ROOT/bp-dev")" = 'unrelated bp-dev sentinel'
test ! -e "$INSTALL_ROOT/.blackpepper-dev/current"
rm "$INSTALL_ROOT/bp-dev"

run_setup >"$TEST_ROOT/first.log" 2>&1
test "$(cat "$INSTALL_ROOT/bp")" = 'production client sentinel'
test "$(cat "$INSTALL_ROOT/bp-host")" = 'production helper sentinel'
test -x "$INSTALL_ROOT/bp-dev"
test ! -e "$INSTALL_ROOT/bp-host-dev"
FIRST_BUNDLE="$(readlink "$INSTALL_ROOT/.blackpepper-dev/current")"
test -x "$FIRST_BUNDLE/bp-dev"
test -x "$FIRST_BUNDLE/bp-host"
test -f "$FIRST_BUNDLE/.blackpepper-dev-bundle"
FIRST_BUILD="$("$FIRST_BUNDLE/bp-host" --version | awk '{print $2}')"
test "$("$INSTALL_ROOT/bp-dev" --version)" = "blackpepper $FIRST_BUILD"
test "$("$INSTALL_ROOT/bp-dev" --help | sed -n 's/^Usage: //p')" = 'bp-dev'

# An identical source tree reuses the verified immutable bundle.
run_setup >"$TEST_ROOT/second.log" 2>&1
SECOND_BUNDLE="$(readlink "$INSTALL_ROOT/.blackpepper-dev/current")"
test "$SECOND_BUNDLE" = "$FIRST_BUNDLE"
test "$(find "$DATA_ROOT" -mindepth 1 -maxdepth 1 -type d ! -name '.staging.*' | wc -l | tr -d ' ')" = 1

# Failure after entrypoint publication but before activation restores the old
# launcher and never moves current.
BEFORE_WRAPPER="$(sha256_file "$INSTALL_ROOT/bp-dev")"
if BLACKPEPPER_TEST_FAIL_BEFORE_ACTIVATION=1 run_setup >"$TEST_ROOT/injected.log" 2>&1; then
  printf '%s\n' 'injected pre-activation failure unexpectedly succeeded' >&2
  exit 1
fi
grep -F 'injected failure before development activation' "$TEST_ROOT/injected.log" >/dev/null
test "$(readlink "$INSTALL_ROOT/.blackpepper-dev/current")" = "$FIRST_BUNDLE"
test "$(sha256_file "$INSTALL_ROOT/bp-dev")" = "$BEFORE_WRAPPER"
test "$("$INSTALL_ROOT/bp-dev" --version)" = "blackpepper $FIRST_BUILD"

# Retention is visible and conservative. Nothing is automatically deleted,
# and explicit pruning refuses current and live bundles.
OLD_BUNDLE="$DATA_ROOT/old-dev-fixture"
mkdir -m 0700 "$OLD_BUNDLE"
printf '%s\n%s\n' 'blackpepper-dev-bundle-v1' 'old-dev-fixture' \
  > "$OLD_BUNDLE/.blackpepper-dev-bundle"
cat > "$OLD_BUNDLE/hold" <<'EOF'
#!/bin/sh
sleep 30
EOF
chmod 0755 "$OLD_BUNDLE/hold"
BLACKPEPPER_DEV_RETAIN_BUILDS=1 run_setup >"$TEST_ROOT/retention.log" 2>&1
grep -F 'No bundles were auto-deleted; provider hooks may use exact paths' "$TEST_ROOT/retention.log" >/dev/null
grep -F 'Retained development storage:' "$TEST_ROOT/retention.log" >/dev/null
grep -F 'retained bundle count exceeds 1' "$TEST_ROOT/retention.log" >/dev/null
run_setup --list-builds > "$TEST_ROOT/list.log"
grep -F $'old-dev-fixture\t' "$TEST_ROOT/list.log" >/dev/null
grep -F $'\tcurrent' "$TEST_ROOT/list.log" >/dev/null

"$OLD_BUNDLE/hold" &
HOLDER_PID=$!
sleep 1
if run_setup --prune old-dev-fixture >"$TEST_ROOT/live-prune.log" 2>&1; then
  printf '%s\n' 'live development bundle was unexpectedly pruned' >&2
  exit 1
fi
grep -F 'used by a running process' "$TEST_ROOT/live-prune.log" >/dev/null
kill "$HOLDER_PID"
wait "$HOLDER_PID" 2>/dev/null || true
HOLDER_PID=""
run_setup --prune old-dev-fixture > "$TEST_ROOT/prune.log"
test ! -e "$OLD_BUNDLE"
if run_setup --prune "${FIRST_BUNDLE##*/}" >"$TEST_ROOT/current-prune.log" 2>&1; then
  printf '%s\n' 'current development bundle was unexpectedly pruned' >&2
  exit 1
fi
grep -F 'refusing to prune the current' "$TEST_ROOT/current-prune.log" >/dev/null

test "$(cat "$INSTALL_ROOT/bp")" = 'production client sentinel'
test "$(cat "$INSTALL_ROOT/bp-host")" = 'production helper sentinel'
test -z "$(find "$INSTALL_ROOT" "$DATA_ROOT" \
  \( -name '.bp-dev.*' -o -name '.current.*' -o -name '.staging.*' \) -print -quit)"

printf '%s\n' 'development install is deterministic, atomic, ownership-safe, and explicitly retained'
